### ISSUE TITLE
Character.summary() involves redundant data

### ISSUE THREAD

**Issue by creaciond** [dracor-org/pydracor#2]
When calling the `summary()` method of `Character` class, it also includes the information on the whole corpus the character is at.

For instance, this piece of code:
```python
character = Character('yakov', 'rus000138')
character.summary()
```
produces [such](https://pastebin.com/Dp7tUz6T) output — feels as if everything after `title: 'Не убий'` is wrong.

Another example:
```python
character = Character('grigorij_dimitrij_lzhedimitrij_samozvanets', 'rus000042')
character.summary()
```
has [same redundant data](https://pastebin.com/YCE9vssR).

**Comment by ldsad7** [comment]
Thanks! Fixed in 0.0.1 version.
