### ISSUE TITLE
If play title is ambiguous, Play() should highlight this

### ISSUE THREAD

**Issue by lehkost** [dracor-org/pydracor#3]
For example, if we do:
```Python
play = Play(play_title='Faust')
```
PyDraCor seems to (randomly?) choose one of the 5 "Faust" plays, but it's unclear which one. Maybe return information about the problem and encourage to use play ID instead?

**Comment by ldsad7** [comment]
Thanks! Fixed in 0.0.1 version. Also added the same warning in case of coinciding play names.
